<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vinothini-PC" name="com.bluemeric.test.GenerateTest" tests="6" failures="0" timestamp="18 Mar 2016 15:56:17 GMT" time="0.201" errors="2">
  <testcase name="getTest" time="0.014" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(GenerateTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(RunTest.java:49)
	at com.bluemeric.test.RunTest.main(RunTest.java:85)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.006" classname="com.bluemeric.test.GenerateTest"/>
  <testcase name="getTest" time="0.039" classname="com.bluemeric.test.GenerateTest"/>
  <testcase name="getTest" time="0.106" classname="com.bluemeric.test.GenerateTest"/>
  <testcase name="getTest" time="0.030" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Passed query parameter is Vidhya. But received reponse = Testing. Parameter is mismatching. Hence failing the test.">
      <![CDATA[java.lang.AssertionError: Passed query parameter is Vidhya. But received reponse = Testing. Parameter is mismatching. Hence failing the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(GenerateTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(RunTest.java:49)
	at com.bluemeric.test.RunTest.main(RunTest.java:85)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.006" classname="com.bluemeric.test.GenerateTest"/>
</testsuite> <!-- com.bluemeric.test.GenerateTest -->
